### ISSUE TITLE
Feature Request: Make the keyboard action bar move together with keypad

### ISSUE THREAD

**Issue by lzhuor** [diegoveloper/flutter_keyboard_actions#123]
The keyboard actions bar doesn't slide up together with the keypad on iOS which isn't very nice.

You can notice that there is a gap when the keypad is sliding up (showing up).

See the issue:
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/14172220/95912997-2df31580-0dd6-11eb-8b4c-46a7aa1d9651.gif)

![image](https://user-images.githubusercontent.com/14172220/95913093-51b65b80-0dd6-11eb-96a7-3c004c2643e9.png)

**Comment by ghenry** [comment]
I was just testing this today on an iPhone XS Max simulator with ios 12.1 and my number keyboard didn't show. Just the action bar. Works on v14.

**Comment by ghenry** [comment]
Ah, #140

**Comment by TheManuz** [comment]
I have this problem too, it's particularly visible if you're implementing a custom keyboard: you will see the keyboard appear suddenly, with no **slide up** animation.

The **slide down** works _almost_ fine, though.
I say almost because it's a resize of the view, instead of a translation, so the children are affected.

**Comment by SteadyAction** [comment]
+1

**Comment by icecandy** [comment]
This has been fixed with the latest update to flutter 2.10. It's a low-level update which somehow just makes it work now with the keyboard header animating in sync with the keyboard.

**Comment by lzhuor** [comment]
Closing it as it's fixed in `v2.10`
