### ISSUE TITLE
Need to reset focus to update the KeyboardActions

### ISSUE THREAD

**Issue by FDuhen** [diegoveloper/flutter_keyboard_actions#128]
Hey,

I've met an edgy case and I can't figure out why it's behaving like this.

When the KeyboardActions is visible on the screen, I can't find a way to update the Widget (the keyboardBarColor or the actions)
The linked focusNode need to lose focus and be focused again to force the redraw of the KeyboardActions

Steps to reproduce : 
- Use the Example Project
- Edit the content.dart
- Create a bool called **_test** with any value
- Duplicate the _buildConfigUpdated, call it _buildConfigUpdatedTest and change any value (for example the keyboardBarColor)
- Edit the build method, if **_test** is true use the _buildConfigUpdated method as a config, else use _buildConfigUpdatedTest
- Create a button calling setState and updating the **_test** value

When clicking the button, and then focusing any FocusNode, everything is alright.
When focusing a FocusNode, click on the button and nothing happens. You have to click on another FocusNode to force the refresh of the KeyboardActions

If you have any tip to update the KeyboardActions without losing focus, it'll help me a lot !

Thank you

**Comment by diegoveloper** [comment]
Hey, add a simple code to reproduce the issue. Thanks

**Comment by diegoveloper** [comment]
it will be closed because we didn't receive any response from the reporter.

**Comment by anamba** [comment]
Not sure if I should create a new issue, I had the exact same question.

I want to have a "Next" action button that is disabled when the input contains < 12 chars and becomes enabled when the input length reaches the target 12 characters. However, after reviewing the code, I didn't see any way to trigger `_overlayEntry!.markNeedsBuild()` via public api, aside from calling unfocus and (later) requestFocus on the associated focus node. And I would have to do this on each keystroke, which is very jarring since it animates.

I tried to implement a fix on my own, but I guess I just don't know enough yet about how all this works. (I've been using Flutter for about 2 months now.)
